services:
  web:
    build: .
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 7777 --reload
    volumes:
      - .:/app
    ports:
      - "7777:7777"
    restart: always
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: taskdev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: