"""Add user_id to tasks

Revision ID: affb19b49818
Revises: 468804e004a1
Create Date: 2025-10-13 20:18:04.751589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affb19b49818'
down_revision: Union[str, Sequence[str], None] = '468804e004a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tasks_title_key'), 'tasks', type_='unique')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_unique_constraint(op.f('tasks_title_key'), 'tasks', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
